FROM ubuntu
RUN apt update && apt install -y wget openjdk-8-jdk-headless python3 python3-pip
RUN wget https://dlcdn.apache.org/spark/spark-3.2.1/spark-3.2.1-bin-hadoop3.2.tgz
RUN tar xfv spark-3.2.1-bin-hadoop3.2.tgz && \
    mv spark-3.2.1-bin-hadoop3.2 $HOME/spark  && \
    rm spark-3.2.1-bin-hadoop3.2.tgz
RUN echo "export SPARK_HOME=$HOME/spark" >> ~/.bashrc && \
    echo "export PATH=$PATH:$HOME/spark/bin" >> ~/.bashrc  && \
    echo "export PYSPARK_PYTHON=python3" >> ~/.bashrc