FROM ubuntu
RUN apt-get update && \
    apt-get install sudo && \
    apt-get install nano && \
    apt-get install -y gnupg2 && \
    apt-get install apt-utils && \
    apt-get install --reinstall ca-certificates -y && \
    apt-get install -y wget && \
    apt-get install -y libgeo-ipfree-perl
RUN echo "deb https://package.mapr.hpe.com/releases/v6.0.0/ubuntu binary trusty" >> /etc/apt/sources.list
RUN echo "deb https://package.mapr.hpe.com/releases/MEP/MEP-6.0.0/ubuntu binary trusty" >> /etc/apt/sources.list
RUN sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys BFDDB60966B3F0D6
RUN sudo apt-get update
RUN wget http://archive.mapr.com/releases/v6.0.0/ubuntu/mapr-client-6.0.0.20171109191718.GA-1.amd64.deb
RUN apt-get  update && apt install -y syslinux
RUN dpkg -i mapr-client-6.0.0.20171109191718.GA-1.amd64.deb